declare namespace AppCssNamespace {
  export interface IAppCss {
    App: string;
    "App-header": string;
    "App-link": string;
    "App-logo": string;
    "App-logo-spin": string;
    area: string;
    "board-card": string;
    "btn-group": string;
    "btn-group-vertical": string;
    "btn-toolbar": string;
    clearfix: string;
    "col-lg-1": string;
    "col-lg-10": string;
    "col-lg-11": string;
    "col-lg-12": string;
    "col-lg-2": string;
    "col-lg-3": string;
    "col-lg-4": string;
    "col-lg-5": string;
    "col-lg-6": string;
    "col-lg-7": string;
    "col-lg-8": string;
    "col-lg-9": string;
    "col-md-1": string;
    "col-md-10": string;
    "col-md-11": string;
    "col-md-12": string;
    "col-md-2": string;
    "col-md-3": string;
    "col-md-4": string;
    "col-md-5": string;
    "col-md-6": string;
    "col-md-7": string;
    "col-md-8": string;
    "col-md-9": string;
    "col-sm-1": string;
    "col-sm-10": string;
    "col-sm-11": string;
    "col-sm-12": string;
    "col-sm-2": string;
    "col-sm-3": string;
    "col-sm-4": string;
    "col-sm-5": string;
    "col-sm-6": string;
    "col-sm-7": string;
    "col-sm-8": string;
    "col-sm-9": string;
    "col-xs-1": string;
    "col-xs-10": string;
    "col-xs-11": string;
    "col-xs-12": string;
    "col-xs-2": string;
    "col-xs-3": string;
    "col-xs-4": string;
    "col-xs-5": string;
    "col-xs-6": string;
    "col-xs-7": string;
    "col-xs-8": string;
    "col-xs-9": string;
    container: string;
    "container-fluid": string;
    "container-full": string;
    "content-title": string;
    contents: string;
    "dl-horizontal": string;
    "form-group": string;
    "form-horizontal": string;
    list: string;
    "list-item": string;
    menu: string;
    "menu-head": string;
    "menu-item": string;
    "menu-list": string;
    "menu-title": string;
    "modal-footer": string;
    "modal-header": string;
    nav: string;
    navbar: string;
    "navbar-collapse": string;
    "navbar-header": string;
    opener: string;
    pager: string;
    panel: string;
    "panel-body": string;
    row: string;
    "side-bar": string;
    "side-bar-inner": string;
    sign: string;
    wrap: string;
  }
}

declare const AppCssModule: AppCssNamespace.IAppCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: AppCssNamespace.IAppCss;
};

export = AppCssModule;
